version: '2'

services:
  auth:
    image: quay.io/nildev/auth:latest
    container_name: auth.nildev
    ports:
        - 8081:8080
    env_file: local.env

  back:
    image: quay.io/steelzz/dosapi:latest
    container_name: dosapi.steelzz
    ports:
        - 8082:8080
    env_file: local.env